
genesis_id = ""
system = "Selfkey"
dependencies = ["Ethereum"]
icon = "selfkey"

[token]
name = "key token"
symbol = "KEY"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Self-Sovereign Identity to instantly access Citizenship by Investment, Company Incorporation, Bank accounts, Exchanges, Token Sales, and much more "

[crowdsales]
start_date = "2017-12-15T00:00:00"
end_date = "2017-12-24T11:59:00"
end_date_plan = "2017-12-15T11:59:00"
genesis_address = [""]
funding_terms = "https://selfkey.org/"
funding_url = "https://selfkey.org/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "selfkey.org"
url = "https://selfkey.org"
tags = ["Main"]

[[links]]
type = "paper"
name = "Selfkey Whitepaper"
url = "https://selfkey.org/whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Selfkey Github"
url = "https://github.com/SelfKeyFoundation"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Selfkey Blog"
url = "https://blog.selfkey.org"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2310691"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "http://twitter.com/SelfKey/"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Selfkey Telegram"
url = "https://t.me/selfkeyfoundation"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/selfkey/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/SelfKeyNetwork"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCsilze3-MhbCY3_QkKul3PQ"
icon = "youtube.png"
tags = ["News"]
